### PR TITLE
Updating to latest version of doorbot

### PR DESCRIPTION
**Pull request by davglass**
This PR pulls in the latest `doorbot@3.0.1` that includes some authentication fixes and improvements. I also dropped the default retries from `15` to `5`, ideally with the latest authentication improvements the retries aren't even needed :)

### CODE REVIEW

**Comment by mrose17** [comment]
@davglass - i thought i had bumped the requirement to 3.0.1 earlier today! i didn't drop the retries, so i just did that. can you see if i am out of sync with you? thanks!

**Comment by davglass** [comment]
@mrose17 the only diff now is that I'm using `^3.0.1` in the package.json instead of `3.0.1`. This way if I release any changes your users get them without you having to release a module update :)

**Comment by mrose17** [comment]
thanks we should be in sync!

**Comment by davglass** [comment]
Awesome, thanks!

**Pull request merged**
